### ISSUE TITLE
Cannot search any of the fields.

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#42]
* Cannot search any of the fields to limit the jobs returned

**Comment by eapearson** [comment]
This one has slipped through the cracks, as in, we never fully implemented search!

See https://github.com/kbase/execution_engine2/issues/85

There are some fundamental design issues here.

We can implement a limited search against ee2 job fields. This would require adding a new search parameter to ee2 which accepts a list of strings (search terms) or a string with space separated search terms. This search expression would be used to create the appropriate filter. That filter wouldn't be complex -- just big. It would need to basically be like (pseudocode):

(username = $term1 or app_id = $term1) and (username = $term2 or app_id = $term2)

So you you can see a problem ... the search should really be against what the user knows, which is  the user real name (and perhaps username), the app title (not app id), module name, and narrative title (there is nothing to search for in a job record for the narrative). I'm sure admins would like to search (or filter -- we could add a filter control for this) by queue.

This is why I've suggested sending job state to ES, where we could create job records which incorporates joined information for the user, app, and narrative.

**Comment by eapearson** [comment]
@bio-boris and @eapearson chatted about this.
We are going to implement this as a filtering rather than search. That is, the front end will provide a tool for allowing the user to filter by one or more values per field, rather than the current implementation of a single search input. 
This will require no additional changes on the ee2 back end. The job browser bff will be modified minimally to whitelist the filter fields involved, and translate the simple field names into the object paths in ee2. The front end will be modified to remove the single search entry, and instead add a switch which opens a filter area which will contain a single search field for each of user, module, app, narrative and queue. The search fields will be searchable dropdowns, since the value being searched will be an exact value comparison to identifiers. Thus, username for user, module id for module, app id for app, queue id for queue.

**Comment by eapearson** [comment]
This has been "fixed" by:
- removing the search input, and the search feature in general
- moving the status filter as well as new per-field filters into a filter dropdown panel
- adding dropdowns for common filter fields: narrative, user, app, app module, app function, client group
- client group is not yet implemented
![Screen Shot 2020-04-29 at 9 09 39 AM](https://user-images.githubusercontent.com/7674378/80619168-29d66580-89f9-11ea-80e6-10dd150f75f0.png)

Tasks left:

- [ ] implement the client group filter
- [ ] add negation to each filter field (probably a column on the right with a negation checkbox)
- [ ] some fields (user) should be omitted from the user search

There are certainly other ways to improve this feature.

**Comment by bio-boris** [comment]
Looks good, looks like there are some checkboxes left, but we can either make that into a new ticket or close this one.

**Comment by eapearson** [comment]
agreed, I'll create a ticket for each of these features:
- negation
- omit user field from my jobs tab
- allow free-form entry for some dropdown fields (perhaps as a separate filter, enabled by ...)
- instead of exposing all filters at once, allow creating a filter by adding filters from a selection list.
