### ISSUE TITLE
minor cosmetic issue

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#47]
![image](https://user-images.githubusercontent.com/1258634/80132716-b39db300-8561-11ea-8f38-fdba5ca34fa6.png)

**Comment by eapearson** [comment]
Fixed in https://github.com/kbase/kbase-ui-plugin-job-browser2/commit/0c9cc23cf68c74f34ee2af93dc74724294b38737

This is an ant-design style issue, in which disabled buttons are wrapped, which breaks alignment within a button group. The fix is simply makes the icon a bit smaller; there is surely a better fix, but since this plugin will eventually be ported to ant design 4 or bootstrap, this is probably as far as we want to go fixing it for now.
